### ISSUE TITLE
V1.1.10 breaks PackageManager

### ISSUE THREAD

**Issue by brettc** [ibm-watson-data-lab/pixiedust#678]
This is inside a jupyter notebook, running python 2.7 on AWS EMR.

### Expected behavior
```python
from pixiedust.packageManager import PackageManager
pkg=PackageManager()
```
Output:
```
Pixiedust version 1.1.9

Pixiedust database opened successfully

Warning: You are not running the latest version of PixieDust. Current is 1.1.9, Latest is 1.1.10

Please copy and run the following command in a new cell to upgrade: !pip install --user --upgrade pixiedust

Please restart kernel after upgrading.
```

### Actual behavior
```python
from pixiedust.packageManager import PackageManager
pkg=PackageManager()
```

Output:
```
Pixiedust version upgraded from 1.1.9 to 1.1.10

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-168d39b97cbe> in <module>()
----> 1 from pixiedust.packageManager import PackageManager
      2 pkg=PackageManager()

/usr/local/lib/python2.7/site-packages/pixiedust/packageManager/__init__.py in <module>()
     15 # -------------------------------------------------------------------------------
     16 
---> 17 from .packageManager import PackageManager
     18 
     19 #shortcut to packageManager

/usr/local/lib/python2.7/site-packages/pixiedust/packageManager/packageManager.py in <module>()
     45 packageStorage = __PackageStorage()
     46 
---> 47 class PackageManager(object):
     48     DOWNLOAD_DIR=os.environ.get("PIXIEDUST_HOME", os.path.expanduser('~')) + "/data/libs"
     49 

/usr/local/lib/python2.7/site-packages/pixiedust/packageManager/packageManager.py in PackageManager()
     56                 return True
     57         return False
---> 58     IS_PIXIEDUST_JAR_ON_JAVA_CLASS_PATH = check_pixiedust_jar(DOWNLOAD_DIR)
     59 
     60     def check_valid(fn):

/usr/local/lib/python2.7/site-packages/pixiedust/packageManager/packageManager.py in check_pixiedust_jar(download_dir)
     52     def check_pixiedust_jar(download_dir):
     53         pixiedust_jar_path = os.path.join(download_dir, "pixiedust.jar")
---> 54         for path in Environment.javaClassPath.split(":"):
     55             if pixiedust_jar_path == path:
     56                 return True

AttributeError: 'NoneType' object has no attribute 'split'

```

### Steps to reproduce the behavior

Install v1.1.10

**Comment by DTAIEB** [comment]
@brettc PackageManager works only if your notebook is connected to Spark. Can you please verify that this is the case. I also think that we should do the check programmatically and display an error message if that's not the case.
I'll use this issue to provide a fix for that.

**Comment by brettc** [comment]
Bear with me, I'm new to spark. All I know (and I show above) is that it works perfectly with 1.1.9, and precisely the same thing breaks with 1.1.10. What you see above is cut and pasted directly from the notebooks.

**Comment by DTAIEB** [comment]
@brettc ok, in a new cell, can you please run the following code and let me know the output
```
from pixiedust.utils.environment import Environment
print("Has spark:", Environment.hasSpark)
print("JavaClassPath:", Environment.javaClassPath)
```
thank you

**Comment by aakashganga** [comment]
how do you append to javaclasspath? I am getting an error PackageManager is disabled because /home/amit.dingare/data/libs is not on the Java Class Path.

**Comment by byFemi** [comment]
To append to java Classpath on Mac OS. Go to your home directory and open the .bash_profile file, inside write:
`export CLASSPATH=$CLASSPATH:/Users/yourname/Documents/projectfolder/`
or wherever you installed it.

I assume this process is similar for other unix systems. 
On windows, I believe there is a path option somewhere in the control panel where one can append
